export const Representatives = {
  coastalProcess: {
    logoSrc: "coastalProcess.png",
    logoHeight: "161px",
    logoWidth: "337px",
    logoAlt: "Coastal Process Logo",
    location: "Louisiana & Mississippi",
    email: "info@coastalprocess.net",
    phone: "225 - 567 - 3120",
    phonePrefill: "tel:2255673120",
  },
  dAndHWaterSystems: {
    logoSrc: "dAndHWaterSystems.png",
    logoHeight: "61px",
    logoWidth: "425px",
    logoAlt: "D&H Water Systems Logo",
    location: "Southern California, Southern Nevada & Arizona",
    email: "melanie@dandhwatersystems.net",
    phone: "760 - 722 - 6893",
    phonePrefill: "tel:7607226893",
  },
  macaulay: {
    logoSrc: "macaulay.png",
    logoHeight: "114px",
    logoWidth: "342px",
    logoAlt: "Macaulay Controls Company Logo",
    location: "Texas",
    email: "info@macaulaycontrols.com",
    phone: "800 - 299 - 1148",
    phonePrefill: "tel:8002991148",
  },
  haynes: {
    logoSrc: "haynes.png",
    logoHeight: "144px",
    logoWidth: "254px",
    logoAlt: "Haynes Equipment Logo",
    location: "Arkansas & Oklahoma",
    email: "tony@haynes-equipment.com",
    phone: "913 - 782 - 4692",
    phonePrefill: "tel:9137824692",
  },
  misco: {
    logoSrc: "misco.png",
    logoHeight: "160px",
    logoWidth: "170px",
    logoAlt: "Misco Water Logo",
    location: "Wyoming & Colorado",
    email: "smarshall@miscowater.com",
    phone: "303 - 309 - 6150",
    phonePrefill: "tel:3033096150",
  },
  tmg: {
    logoSrc: "tmg.png",
    logoHeight: "86px",
    logoWidth: "138px",
    logoAlt: "TMG Services Logo",
    location: "Oregon, Washington, Idaho, Montana",
    email: "tmg@tmgservices.net",
    phone: "800 - 562 - 2130",
    phonePrefill: "tel:8005622130",
  },
  tc: {
    logoSrc: "tc.png",
    logoHeight: "115px",
    logoWidth: "325px",
    logoAlt: "TC Sales and Service Logo",
    location: "Utah",
    email: "contact@tcsalesco.com",
    phone: "801 - 201 - 3121",
    phonePrefill: "tel:8012013121",
  },
  pyrz: {
    logoSrc: "pyrz.png",
    logoHeight: "103px",
    logoWidth: "365px",
    logoAlt: "PYRZ Water Supply Logo",
    location:
      "Pennsylvania, West Virginia, New York, New Jersey, Delaware, Maryland & Virginia",
    email: "sales@pyrzwater.com",
    phone: "215 - 256 - 8430",
    phonePrefill: "tel:2152568430",
  },
  petersonAndMatz: {
    logoSrc: "petersonAndMatz.png",
    logoHeight: "94px",
    logoWidth: "460px",
    location: "Michigan, Illinois, Wisconsin & Indiana",
    email: "cathy.piazza@petersonandmatz.com",
    phone: "847 - 844 - 4405",
    phonePrefill: "tel:8478444405",
  },
  hpThompson: {},
};
